import { rest } from 'msw';

export const handlers = [
  rest.get(
    /^https?:\/\/(dev-)?internal-api\.hub\.(aws)?zum\.com\/media\/recommend\b/,
    (req, res, ctx) => {
      return res(
        ctx.json({
          mediaList: [
            {
              mediaIdx: 201,
              name: '계란비누',
              hubUrl: 'eggsoap',
              urlLabel: '',
              url: '',
              socialUrl: '',
              type: '',
              profile: '열심히 쓰면 잘 쓸 수 있을까',
              image:
                'http://static.hubzum.zumst.com/hubzum/2016/03/07/18/95c2ff61c6254c709292dbb77e8584cc.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2016-03-07T18:22:00',
              updatedAt: '2016-04-06T10:09:10',
              updater: '임효진',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 88,
              name: '공감공유',
              hubUrl: 'rokmc1062',
              urlLabel: '',
              url: 'http://rokmc1062.tistory.com',
              socialUrl: '',
              type: '티스토리 블로거 / 직장인',
              profile: "티스토리 우수블로그, 대한민국 블로그 어워드 '여행' 우수블로거",
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/1f3b94081d5d46a889bfeeb8e0137b72.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-07-06T16:26:26',
              updatedAt: '2015-12-29T12:20:27',
              updater: '박정은',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 65,
              name: '권빈',
              hubUrl: 'companyjit',
              urlLabel: '',
              url: 'http://companyjit.tistory.com/',
              socialUrl: '',
              type: '렛유인 대표강사',
              profile: 'IT기업 면접 전문가로 IT칼럼쓰고 있습니다.',
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/84e67281613642798437c41ae7fb295c.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-06-19T04:30:00',
              updatedAt: '2016-11-22T11:24:32',
              updater: '석지은',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 6,
            },
            {
              mediaIdx: 579,
              name: '기묘한 ',
              hubUrl: 'invest_52',
              url: 'https://page.stibee.com/subscriptions/41037?groupIds=115679 ',
              profile:
                '現)뉴스레터 트렌드라이트 발행인\n\n- 저서 : 『기묘한 이커머스 이야기』(프리덤북스)\n\n\n국내 최고 커머스 뉴스레터 『트렌드라이트』의 발행인 기묘한입니다. 현재 커머스 업계에서 전략 직무로 일을 하고 있으며, 업계와 대중 간의 간극을 줄이는 데 기여하고자 합니다.',
              image: 'https://finance.zumst.com/writing/e4f0b9f6_프로필 이미지.jpg ',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: false,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              associatedLinksJson: '',
              state: 'ACTIVE',
              createdAt: '2023-12-29T10:00:00',
              updatedAt: '2023-12-29T18:39:05',
              updater: '차용현',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 39,
              name: '김국현',
              hubUrl: 'goodhyun',
              urlLabel: '',
              url: 'https://editoy.com/',
              socialUrl: '',
              type: '에디토이 대표',
              profile:
                "줌닷컴, 조선일보, 한겨레 등에 글을 연재중이며 '오프라인의 귀환' 등 유수의 저서가 있음.",
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/b104ee7808064c7fa9d3d60c914948bc.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: true,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-06-10T17:31:00',
              updatedAt: '2019-02-18T11:41:45',
              updater: '유수영',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 222,
              name: '김석기',
              hubUrl: 'neokim',
              urlLabel: '',
              url: '',
              socialUrl: 'http://facebook.com/neokim',
              type: '동양대학교 교수',
              profile: 'IT 산업의 트랜드와 인사이트로 IT의 미래를 예측한다. ',
              image:
                'http://static.hubzum.zumst.com/hubzum/2016/07/18/17/d53a1f2b82594e6db08739b3cb74f283.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: true,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2016-07-18T17:21:00',
              updatedAt: '2016-09-13T13:51:59',
              updater: '임효진',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 120,
              name: '김선인',
              hubUrl: 'stpetro',
              urlLabel: '',
              url: 'http://blog.naver.com/stpetro',
              socialUrl: '',
              type: '수필가 / 여행작가',
              profile:
                '잡지 &lt;여행작가&gt;에 힐링&nbsp;섬기행, &lt;현대수필&gt;에 수사에세이&nbsp;연재 중',
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/9c9f54339b7c41c2a92fd975f4cebdc5.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: true,
              associatedLinksJson:
                '[{"title":" ","url":"https://trip.zum.com/jeju/","thumbLink":"http://static.hubzum.zumst.com/hubzum/2020/08/24/10/11e2f493690d444389cc8fd067e419a6.jpg"}]',
              state: 'ACTIVE',
              createdAt: '2015-07-24T10:51:00',
              updatedAt: '2020-08-24T10:16:24',
              updater: '석지은',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 146,
              name: '김승열',
              hubUrl: 'mobizen',
              urlLabel: '',
              url: 'http://www.mobizen.pe.kr/',
              socialUrl: '',
              type: '',
              profile:
                '모바일왕국을 꿈꾸는 변방의 블로거<br>다양한 모바일 서비스 업무를 수행해왔다.&nbsp;',
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/e4907b05dfca49c6a7b78cd12eaa56d7.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: true,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-08-18T16:25:47',
              updatedAt: '2015-12-24T16:51:20',
              updater: '공손이',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 141,
              name: '김연일',
              hubUrl: 'yonil',
              urlLabel: '',
              url: '',
              socialUrl: '',
              type: '변방작업자',
              profile:
                '영화를 음악과 사운드 위주로 보는 글. 몇 박자 늦게, 근과거의 영화들을 주로 다룹니다.',
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/578580d05cc94cdd8d43f6f6c9a9bf64.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: true,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-07-31T09:15:45',
              updatedAt: '2015-12-24T16:50:15',
              updater: '공손이',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 170,
              name: '김우승',
              hubUrl: 'kimws',
              urlLabel: '',
              url: 'http://www.kimws.com',
              socialUrl: '',
              type: '',
              profile: '줌인터넷 사장&nbsp;<br> 최근엔 검색,빅데이터,플랫폼이 주요 관심사',
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/24/16/8400c9a9570242248f2668e816ab23fb.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: true,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-10-28T13:45:00',
              updatedAt: '2016-12-27T10:48:14',
              updater: '박정은',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 203,
              name: '김은지',
              hubUrl: 'eunjidan',
              urlLabel: '',
              url: '',
              socialUrl: '',
              type: '',
              profile:
                "It's not what you look at that matters, it's what you see. - Henry David Thoreau&nbsp;",
              image:
                'http://static.hubzum.zumst.com/hubzum/2016/03/14/13/c0f6b334c1844313bd50d5772c2c19e4.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: true,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2016-03-14T13:47:00',
              updatedAt: '2016-04-12T13:53:51',
              updater: '박정은',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 224,
              name: '김정훈',
              hubUrl: 'yoyolove',
              urlLabel: '',
              url: '',
              socialUrl: 'http://instagram.com/oilfree84',
              type: '작가',
              profile: '불만보단 불안을 즐깁니다. 요즘남자요즘연애 [소담] 출간',
              image:
                'http://static.hubzum.zumst.com/hubzum/2016/08/01/17/b644edf91f544ca9aba06992d1f5952c.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: true,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: true,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2016-08-01T17:40:00',
              updatedAt: '2019-01-17T15:00:50',
              updater: '이새롬',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 181,
              name: '나용',
              hubUrl: '2na0',
              urlLabel: '',
              url: 'http://2na0.com',
              socialUrl: '',
              type: '',
              profile:
                '‘나용이의 구석구석 방방곡곡’ 블로그를 운영하며 여행 이야기를 담습니다.&nbsp;',
              image:
                'http://static.hubzum.zumst.com/hubzum/2015/12/10/16/0981c4ec92e14ef6960312cd7e6ef996.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: true,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-12-10T16:15:51',
              updatedAt: '2016-02-01T16:51:51',
              updater: '박정은',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 596,
              name: '동상이몽회관 ',
              hubUrl: 'invest_70',
              url: 'https://www.ds2m.xyz/ ',
              profile:
                '(Futurist) 증권사 출신 디지털자산 운용 스타트업 CSO\n\n(해리킴) 연구원 출신 벤처캐피탈 투자심사역 (S벤처스 투자본부)\n\n(A.I) 자산운용사 출신 벤처캐피탈 투자심사역 (S파트너스 투자본부)\n\n\n동상이몽회관은 창업자와 투자자의 생각을 이어 더 나은 철학을 만드는\n\n공간입니다. 비상장 벤처 씬의 현직자로서 투자에 대한 생각을 이야기합니다.',
              image: 'https://finance.zumst.com/writing/a1379346_ds2m logo.jpg ',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: false,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              associatedLinksJson: '',
              state: 'ACTIVE',
              createdAt: '2023-12-29T10:00:00',
              updatedAt: '2023-12-29T18:38:41',
              updater: '차용현',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
            {
              mediaIdx: 184,
              name: '매리킴',
              hubUrl: 'marykim',
              urlLabel: '',
              url: '',
              socialUrl: '',
              type: '스테이지톡',
              profile:
                '러시아문학과 연극학을 공부하고, 무대 뒤와 객석을 오가며 공연에 관련된 글을 씁니다.&nbsp;',
              image:
                'http://static.hubzum.zumst.com/hubzum/2016/01/28/10/1dc4b00a6769425e83fe6d0501c47f2e.jpg',
              supportedPlatform: 'ALL',
              providerType: 'WRITER',
              isOpenHubzum: false,
              isOpenSearch: true,
              isOpenMediaList: true,
              isDirectLink: true,
              isStartPage: false,
              isAssociatedLinkExpose: false,
              state: 'ACTIVE',
              createdAt: '2015-12-10T16:22:28',
              updatedAt: '2016-01-28T10:04:38',
              updater: '임효진',
              providerTypeQuality: 4,
              mediaNameQuality: 1,
              contentCount: 0,
            },
          ],
        }),
      );
    },
  ),
];
